name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Enviar para o S3
        run: |
          aws s3 sync dist/ s3://nuvme-price

      - name: Invalidar cache do CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E19RJ8OHOW5WB6 --paths "/*"
